### PR TITLE
Fix build on fdroid

### PR DESCRIPTION
**Pull request by innir**
Hi Arne,

I got a mail that the build is failing on the fdroid build system. It seems that gradle 3.0.0 is not in the mavenCentral() repo but in the google() repo - I added it now.

Here the full mail for reference:

> 
> 
> michel@debian:~/git/fdroiddata$ fdroid build -vl de.arnefeil.bewegungsmelder
> Clonage dans 'build/de.arnefeil.bewegungsmelder'...
> INFO: Building version 2.0.3 (140632) of de.arnefeil.bewegungsmelder
> INFO: Getting source for revision 5c1ace248217bb5902509536d8d9b26dbd009295
> INFO: Creating local.properties file at build/de.arnefeil.bewegungsmelder/local.properties
> INFO: Cleaned build.gradle of keysigning configs at build/de.arnefeil.bewegungsmelder/build.gradle
> INFO: Cleaning Gradle project...
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'de.arnefeil.bewegungsmelder'.
>> Could not resolve all files for configuration ':classpath'.
>    > Could not find com.android.tools.build:gradle:3.0.0.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
>          https://repo1.maven.org/maven2/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
>      Required by:
>          project :
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 15s
> ERROR: Could not build app de.arnefeil.bewegungsmelder: Error cleaning de.arnefeil.bewegungsmelder:2.0.3
> ==== detail begin ====
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'de.arnefeil.bewegungsmelder'.
>> Could not resolve all files for configuration ':classpath'.
>    > Could not find com.android.tools.build:gradle:3.0.0.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
>          https://repo1.maven.org/maven2/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
>      Required by:
>          project :
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 15s
> ==== detail end ====
> INFO: Finished.
> INFO: 1 builds failed
> 
> I think you need to add the google() repo in https://github.com/arnef/bewegungsmelder-android/blob/master/build.gradle
> 
> Could you please tag releases for the bot to automatically update metadata files?
> 

They also ask you to tag releases so they can automatically build new versions. Would you do that?

Best,
Philip

### CODE REVIEW

**Comment by innir** [comment]
The need for the google() repp is also mentioned here: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html

**Review by mimi89999 — APPROVED** [review]

**Comment by innir** [comment]
@arnef Could you please review/merge my pull request? Would be great to be able to use Bewegungsmelder again.

**Comment by innir** [comment]
@arnef Thanks!

**Comment by mimi89999** [comment]
@arnef Could you please use release tags? Would make auto updates easier...

**Comment by arnef** [comment]
sure. it's done

**Pull request merged**
